version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - docker --version

      - ECR_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - REPOSITORY_URI=${ECR_URI}/${ECR_REPO_NAME}

      - aws ecr get-login-password --region $AWS_REGION |
        docker login --username AWS --password-stdin $ECR_URI

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building Docker image with build args..."

      - docker build --build-arg VITE_APP_API_ENDPOINT_URL=$VITE_APP_API_ENDPOINT_URL --build-arg VITE_APP_TMDB_V3_API_KEY=$VITE_APP_TMDB_V3_API_KEY -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing Docker image to ECR..."

      - docker push $REPOSITORY_URI:$IMAGE_TAG

      - echo "Creating imagedefinitions.json for ECS..."

      - printf '[{"name":"%s","imageUri":"%s"}]' \
          $ECR_REPO_NAME \
          $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
